### PR TITLE
Add docs for declaratively managing orgs/spaces/roles

### PR DESCRIPTION
**Pull request by akrishna90**
## Is there a related GitHub Issue?

#1569 

## What is this change about?

Added docs for declaratively managing orgs/spaces/roles

## Does this PR introduce a breaking change?

No

## Acceptance Steps

See issue #1569

### CODE REVIEW

**Comment by akrishna90** [comment]
Its easier to read the docs here - https://github.com/cloudfoundry/korifi/blob/issues/1569/INSTALL.md#declaratively-manage-orgs-spaces-and-roles

**Comment by gcapizzi** [comment]
Also: shall we be calling this "declarative", given an org and a space can't be applied together, due to the hard dependency of the space on the org being reconciled? People won't be able to put all those YAML fragments in the same file and apply them, so maybe this is more about using the CRDs API directly vs the REST API?

**Comment by akrishna90** [comment]
Thanks @gcapizzi for feedback. We ended up pulling the docs to a separate document and presented both `kubectl` & `kapp` ways of creating orgs/spaces and rolebindings.

**Review by clintyoshimura — APPROVED** [review]
LGTM

**Pull request merged**
