### PR TITLE
Set CPU requests and limits based on app memory

### PR DESCRIPTION
**Pull request by clintyoshimura**
## Is there a related GitHub Issue?
#1187

## What is this change about?
Set the StatefulSet CPU requests and limits based on the app memory in RunWorkloads

## Does this PR introduce a breaking change?
no

## Acceptance Steps
See issue

## Tag your pair, your PM, and/or team
@acosta11

### CODE REVIEW

**Review by acosta11 — APPROVED** [review]
LGTM, and we added a note for the team to consider our strategy before merging so leaving auto-merge turned off for now.

**Comment by danail-branekov** [comment]
@kieron-dev and I had a look at the PR and have a couple of concerns:

1) The cpu/memory ratio is not configurable, i.e. an app would always get 100 millicores per 1G of memory. Would such a ratio always work for every cluster? If the ratio is configurable, then operators would be able to do the maths so that they accomodate the apps they expect to run on the cluster.
2) Do we really need to set cpu limits? Back in time when we were working on the Garden CPU throttling feature we came to the conclusion that
    a) setting hard limits on containers causes initialisation/startup routines for apps to occasionally timeout (for example, Spring apps)
    b) that leaves CPU underutilised as there would be noone to use it (imagine a cluster with one or two apps that are limited to a CPU)
    c) it is hard (even impossible) to come up with reasonable limits that would allow apps to burst effectively while restricting noisy neighbours

**Comment by clintyoshimura** [comment]
@danail-branekov @kieron-dev @emalm @tcdowney @acosta11 
After some discussion, we added a proposal regarding the CPU limit calculation on the issue (https://github.com/cloudfoundry/korifi/issues/1187#issuecomment-1183539480).
We can continue the discussion there.
Thanks

**Comment by clintyoshimura** [comment]
Based on discussion of updated issue requirements, closing this PR in favor of #1382

**Pull request closed without merging**
