### PR TITLE
Bump to go 1.21

### PR DESCRIPTION
**Pull request by matt-royal**
## Is there a related GitHub Issue?

#2768 

## What is this change about?

Bumping go to 1.21. The current version is 1.21.4 and I have had no issues with the tests locking up or failing on my local M1 Mac or in a docker container running `golang:1.21`.

## Does this PR introduce a breaking change?

No

## Acceptance Steps

Tests continue to pass

### CODE REVIEW

**Comment by danail-branekov** [comment]
@matt-royal well, it seems that tests locked up here in actions - controllers tests have been terminated after not completing for 6 hours. We have an [issue](https://github.com/cloudfoundry/korifi/issues/2768) in the backlog to investigate, unfortunately we have no idea what might be causing it. 
Our hope is that this eventually gets sorted out by golang maintainers (as such sort of issues are terrible to troubleshoot), it seems this is not the case yet.

**Review by davewalter — APPROVED** [review]

**Comment by matt-royal** [comment]
I was able to bump the go version to `1.21.4` by setting `check-latest: true` in the git workflow. Unfortunately, the tests still appear to be hanging.

**Comment by danail-branekov** [comment]
@matt-royal just being curious, why do you think that latest golang could have solved the issue? Did you see something related in the latest release notes?

**Comment by matt-royal** [comment]
@danail-branekov 1.21.4 included a number of bug fixes, so it seemed possible, but the main reason was that the tests don't hang on my Mac with 1.21.4, nor do they hang in a Docker container with golang 1.21.4. I suppose that whatever is happening on github can't be reproduced that way.

**Comment by matt-royal** [comment]
Given the ongoing issue with the controller tests, I'm going to close this PR.

**Comment by danail-branekov** [comment]
I wonder whether that could be something Linux specific - we are seeing those tests getting stuck on concourse, actions, our Linux VMS... they are all ubuntus

**Comment by matt-royal** [comment]
@danail-branekov The only linux environment I've used locally to test it was a `golang:1.21` image, which is not based on Ubuntu. I'll try running it against an Ubuntu image and report back

**Comment by matt-royal** [comment]
I ran into trouble running the tests on ubuntu and today's my last day working on Korifi, so I'll leave this as a mystery for others to solve.

**Pull request closed without merging**
